[package]
authors = ['Alex Rozgo <alex.rozgo@gmail.com>']
build = 'build.rs'
description = 'SugarFunge blockchain node'
edition = '2018'
homepage = 'https://sugarfunge.io'
license = 'Unlicense'
name = 'sf-node'
repository = 'https://github.com/SugarFunge/sf-node'
version = '0.1.0'

[[bin]]
name = 'sf-node'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
structopt = "0.3.8"
# serde = { version = "1.0.119", features = ["derive"] }
serde_json = "1.0"

# Substrate dependencies
sc-cli = { features = ["wasmtime"], git = "https://github.com/paritytech/substrate", version = "0.9.0" }
sp-core = { git = "https://github.com/paritytech/substrate", version = "3.0.0" }
sc-executor = { features = ["wasmtime"], git = "https://github.com/paritytech/substrate", version = "0.9.0" }
sc-service = { features = ["wasmtime"], git = "https://github.com/paritytech/substrate", version = "0.9.0" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", version = "3.0.0" }
sc-keystore = { git = "https://github.com/paritytech/substrate", version = "3.0.0" }
sp-inherents = { git = "https://github.com/paritytech/substrate", version = "3.0.0" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", version = "3.0.0" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", version = "3.0.0" }
sc-consensus-aura = { git = "https://github.com/paritytech/substrate", version = "0.9.0" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", version = "0.9.0" }
sp-consensus = { git = "https://github.com/paritytech/substrate", version = "0.9.0" }
sc-consensus = { git = "https://github.com/paritytech/substrate", version = "0.9.0" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", version = "0.9.0" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", version = "3.0.0" }
sc-client-api = { git = "https://github.com/paritytech/substrate", version = "3.0.0" }
sp-runtime = { git = "https://github.com/paritytech/substrate", version = "3.0.0" }

# These dependencies are used for the SugarFunge Node's RPCs
jsonrpc-core = "15.1.0"
sc-rpc = { git = "https://github.com/paritytech/substrate", version = "3.0.0" }
sp-api = { git = "https://github.com/paritytech/substrate", version = "3.0.0" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate", version = "0.9.0" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", version = "3.0.0" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", version = "3.0.0" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", version = "0.9.0" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", version = "3.0.0" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", version = "3.0.0" }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { git = "https://github.com/paritytech/substrate", version = "3.1.0" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", version = "3.0.0" }

# SugarFunge deps
sf-primitives = { path = "../primitives", default-features = false }
sf-runtime = { path = '../runtime' }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", version = "3.0.0" }

[features]
default = []
runtime-benchmarks = ['sf-runtime/runtime-benchmarks']
